- hosts: instance
  tasks:
    - name: download kind
      get_url:
        url: https://github.com/kubernetes-sigs/kind/releases/download/v0.9.0/kind-linux-amd64
        dest: /usr/local/bin/kind
        mode: a+x

    - name: set deploy environment
      set_fact:
        deploy_environment: 'kubevirtci-testing'

    - name: Include overlay config
      include_vars:
        file: "{{ deploy_environment }}.yml"

    - name: set local project infra root
      set_fact:
        local_project_infra_root: '{{ playbook_dir}}/../../../../../'

    - name: create project-infra dir
      file:
        path: '{{ project_infra_root }}'
        state: directory

    - name: upload project-infra files
      synchronize:
        src: '{{ local_project_infra_root }}'
        dest: '{{ project_infra_root }}'
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=venv"

    - name: Launch Docker in Docker
      shell: |
        /usr/local/bin/start_dind.sh
      changed_when: false

    - name: Launch cluster
      command: kind create cluster
      changed_when: false
      when: "'kubevirtci' in deploy_environment"

    - name: set secrets dir
      set_fact:
        secrets_dir: '{{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}/secrets/'

    - name: Create secrets dir
      file:
        path: '{{ secrets_dir }}'
        state: directory

    - name: Create kubeconfig secret
      copy:
        src: '{{ kubeconfig_path }}'
        dest: '{{ secrets_dir }}/kubeconfig'
        remote_src: true
