apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-daemon-mirror-config
data:
  docker: |
{{ lookup('file', '{{ manifest_base }}/files/docker-daemon-mirror.conf' ) | indent(width=4, indentfirst=True) }}

  docker-proxy: |
{{ lookup('file', '{{ manifest_base }}/files/docker-daemon-mirror-proxy.conf' ) | indent(width=4, indentfirst=True) }}
