---
- set_fact:
    manifest_base: "{{ role_path }}"
- include_role:
    name: kubernetes_crud
  vars:
    steps: "{{ deploy_steps }}"
    default_kubeconfig_path: "{{ targetKubeconfig }}"
    default_context:  '{{ targetContext }}'
    default_namespace: '{{ targetNamespace }}'

